#!/usr/bin/env bash
# Install ArmOS's qemu-system-arm (with stm32h745-carrier) for the current user.
#
# Puts a launcher on PATH so you can run:
#   qemu-system-arm -machine stm32h745-carrier ...
# like any other QEMU.
#
# Default install: ~/.local/bin/qemu-system-arm  (no root required).
# Override:
#   ARMOS_QEMU_INSTALL_BIN=/usr/local/bin ./install-global.sh   # may need sudo
#   ARMOS_QEMU_INSTALL_NAME=qemu-system-arm-armos ./install-global.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN_SRC="${ROOT}/qemu/build/qemu-system-arm"
DEPS_LIB="${ROOT}/.deps/prefix/usr/lib64"
INSTALL_DIR="${ARMOS_QEMU_INSTALL_BIN:-${HOME}/.local/bin}"
INSTALL_NAME="${ARMOS_QEMU_INSTALL_NAME:-qemu-system-arm}"
LAUNCHER="${INSTALL_DIR}/${INSTALL_NAME}"

echo "==> ensuring custom QEMU is built" >&2
"${ROOT}/scripts/ensure-qemu.sh" >/dev/null

if [[ ! -x "${BIN_SRC}" ]]; then
  echo "error: missing ${BIN_SRC}" >&2
  exit 1
fi

mkdir -p "${INSTALL_DIR}"

# Launcher: pin LD_LIBRARY_PATH for staged deps (SDL/glib/pixman) and exec the
# in-tree binary so rebuilds are picked up without reinstalling.
{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n' '# Generated by ArmOS qemu-stm32h745/scripts/install-global.sh'
  printf '%s\n' '# Re-run that script after moving the ArmOS tree.'
  printf '%s\n' 'set -euo pipefail'
  printf 'ARMOS_QEMU_BIN=%q\n' "${BIN_SRC}"
  printf 'ARMOS_QEMU_LIB=%q\n' "${DEPS_LIB}"
  cat <<'EOF'
if [[ ! -x "${ARMOS_QEMU_BIN}" ]]; then
  echo "error: ArmOS QEMU binary missing: ${ARMOS_QEMU_BIN}" >&2
  echo "  rebuild:  (cd …/ArmOS && qemu-stm32h745/scripts/ensure-qemu.sh)" >&2
  echo "  reinstall: qemu-stm32h745/scripts/install-global.sh" >&2
  exit 1
fi
if [[ -d "${ARMOS_QEMU_LIB}" ]]; then
  export LD_LIBRARY_PATH="${ARMOS_QEMU_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi
exec "${ARMOS_QEMU_BIN}" "$@"
EOF
} > "${LAUNCHER}"
chmod +x "${LAUNCHER}"

echo "==> installed launcher: ${LAUNCHER}" >&2
echo "    -> ${BIN_SRC}" >&2

# Ensure ~/.local/bin is on PATH for common shells (idempotent).
ensure_path_line() {
  local rc="$1"
  local line='export PATH="$HOME/.local/bin:$PATH"'
  [[ -f "${rc}" ]] || return 0
  # Only treat an *active* (uncommented) PATH export as present.
  if grep -qE '^[[:space:]]*export PATH=.*\.local/bin' "${rc}" 2>/dev/null; then
    return 0
  fi
  {
    echo ""
    echo "# ArmOS custom qemu-system-arm (stm32h745-carrier)"
    echo "${line}"
  } >> "${rc}"
  echo "==> added ~/.local/bin to PATH in ${rc}" >&2
}

if [[ "${INSTALL_DIR}" == "${HOME}/.local/bin" ]]; then
  ensure_path_line "${HOME}/.bashrc"
  ensure_path_line "${HOME}/.zshrc"
  # Current session
  case ":${PATH}:" in
    *":${HOME}/.local/bin:"*) ;;
    *) export PATH="${HOME}/.local/bin:${PATH}" ;;
  esac
fi

export LD_LIBRARY_PATH="${DEPS_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
if ! "${LAUNCHER}" -machine help 2>/dev/null | grep -q 'stm32h745-carrier'; then
  echo "error: installed launcher does not expose stm32h745-carrier" >&2
  exit 1
fi

echo "==> ok: '${INSTALL_NAME}' provides stm32h745-carrier" >&2
echo "    try:  ${INSTALL_NAME} -machine help | grep stm32h745" >&2
if [[ "${INSTALL_DIR}" == "${HOME}/.local/bin" ]]; then
  echo "    note: open a new shell (or: export PATH=\"\$HOME/.local/bin:\$PATH\")" >&2
  echo "    distro binary still at: /usr/bin/qemu-system-arm" >&2
fi
